# Generated by Django 6.1.1 on 2026-09-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('co', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentprocessing',
            name='extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentprocessing',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
