# Generated by Django 6.1.1 on 2026-09-30 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('borrower', 'Borrower'), ('lender', 'Lender')], default='borrower', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('alternate_phone_number', models.CharField(blank=True, max_length=15)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=255)),
                ('mother_name', models.CharField(blank=True, max_length=255)),
                ('spouse_name', models.CharField(blank=True, max_length=255)),
                ('number_of_dependents', models.PositiveIntegerField(default=0)),
                ('employment_type', models.CharField(blank=True, choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business', 'Business'), ('unemployed', 'Unemployed'), ('student', 'Student')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('employer_or_business_name', models.CharField(blank=True, max_length=255)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('residence_type', models.CharField(blank=True, choices=[('owned', 'Owned'), ('rented', 'Rented'), ('family', 'Family'), ('company_provided', 'Company Provided')], max_length=20)),
                ('years_at_current_address', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('has_existing_loan', models.BooleanField(default=False)),
                ('existing_monthly_emi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('amount_willing_to_lend', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_lending_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximum_lending_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lender_total_asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('lender_bank_name', models.CharField(blank=True, max_length=255)),
                ('lender_account_number', models.CharField(blank=True, max_length=20)),
                ('lender_ifsc_code', models.CharField(blank=True, max_length=11)),
                ('preferred_loan_type', models.CharField(blank=True, choices=[('personal', 'Personal Loan'), ('home', 'Home Loan'), ('auto', 'Auto Loan'), ('education', 'Education Loan'), ('business', 'Business Loan')], max_length=20)),
                ('risk_preference', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='common_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
