# Generated by Django 6.1.1 on 2026-10-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_commonprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonprofile',
            name='aadhaar_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='address_line',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='amount_willing_to_lend',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='bank_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='employer_or_business_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='employment_type',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self Employed'), ('business', 'Business'), ('unemployed', 'Unemployed'), ('student', 'Student')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='father_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='ifsc_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='lender_account_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='lender_bank_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='lender_ifsc_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='lender_total_asset_value',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='maximum_lending_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='minimum_lending_amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='mother_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='occupation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='pan_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='preferred_loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('home', 'Home Loan'), ('auto', 'Auto Loan'), ('education', 'Education Loan'), ('business', 'Business Loan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='residence_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('rented', 'Rented'), ('family', 'Family'), ('company_provided', 'Company Provided')], max_length=20),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='risk_preference',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='total_asset_value',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='years_at_current_address',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='commonprofile',
            name='years_of_experience',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
