# Generated by Django 6.1.1 on 2026-09-09 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('name_as_per_aadhaar', models.CharField(blank=True, max_length=150)),
                ('name_as_per_pan', models.CharField(blank=True, max_length=150)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('pan_number', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address_line', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('employment_type', models.CharField(blank=True, choices=[('SALARIED', 'Salaried'), ('SELF_EMPLOYED', 'Self Employed'), ('BUSINESS', 'Business'), ('STUDENT', 'Student'), ('RETIRED', 'Retired'), ('OTHER', 'Other')], max_length=20)),
                ('employer_or_business_name', models.CharField(blank=True, max_length=200)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('annual_gross_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('existing_monthly_obligations', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount_requested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('loan_purpose', models.CharField(blank=True, max_length=200)),
                ('loan_purpose_details', models.TextField(blank=True)),
                ('requested_tenure_months', models.PositiveIntegerField(blank=True, null=True)),
                ('repayment_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-weekly')], default='MONTHLY', max_length=20)),
                ('application_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FROZEN', 'Frozen'), ('UNDER_VERIFICATION', 'Under Verification'), ('REVERIFICATION', 'Reverification Required'), ('VERIFIED', 'Verified'), ('RISK_ASSESSMENT', 'Risk Assessment'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrower_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN Card'), ('ITR', 'Income Tax Return'), ('INCOME_COMPUTATION', 'Income Computation'), ('PASSPORT', 'Passport'), ('ADDRESS_PROOF', 'Address Proof'), ('ELECTRICITY_BILL', 'Electricity Bill'), ('MAINTENANCE_BILL', 'Maintenance Bill'), ('BANK_STATEMENT', 'Bank Statement'), ('SALARY_SLIP', 'Salary Slip'), ('FORM_16', 'Form 16'), ('BUSINESS_PROOF', 'Business Proof'), ('LOAN_REPAYMENT_STATEMENT', 'Previous Loan Repayment Statement'), ('OTHER', 'Other')], max_length=40)),
                ('document', models.FileField(upload_to='borrower_documents/')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVERIFICATION', 'Reverification Required')], default='PENDING', max_length=20)),
                ('extracted_name', models.CharField(blank=True, max_length=150)),
                ('extracted_document_number', models.CharField(blank=True, max_length=50)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('extracted_income', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='borrower.borrower')),
            ],
        ),
    ]
