<<<<<<< HEAD
# Generated manually to fix missing migration
=======
# Generated by Django 6.1.1 on 2026-09-09
>>>>>>> 6011aeb4929af2d818f28ed1ce180979b7e0c025

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('borrower', '0001_initial'),
=======
        ("borrower", "0001_initial"),
>>>>>>> 6011aeb4929af2d818f28ed1ce180979b7e0c025
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='borrower',
            name='cibil_score',
=======
            model_name="borrower",
            name="cibil_score",
>>>>>>> 6011aeb4929af2d818f28ed1ce180979b7e0c025
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
