# Generated by Django 6.1.1 on 2026-09-09 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borrower_cibil_score'),
        ('borrower', '0002_borrowerverification'),
    ]

    operations = [
    ]
