# Generated by Django 6.1.1 on 2026-09-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrower', '0002_borrowerverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='cibil_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
