# Generated by Django 6.1.1 on 2026-09-09 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('available_funds', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('risk_tolerance', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lender_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('DOCS_VERIFIED', 'Documents Verified'), ('READY_FOR_LENDER', 'Ready for Lender Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='READY_FOR_LENDER', max_length=30)),
                ('ai_trust_score', models.IntegerField(default=0)),
                ('ai_risk_level', models.CharField(default='LOW', max_length=20)),
                ('ai_recommended_terms', models.JSONField(blank=True, default=dict)),
                ('ai_risk_breakdown', models.JSONField(blank=True, default=dict)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funded_loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
